name: loja_virtual
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.8
  firebase_core: ^2.19.0
  provider: ^6.0.5
  another_carousel_pro: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lint: ^2.1.2

flutter:
  uses-material-design: true
